version: '3.1'

services:
  nodejs:
    depends_on:
      - postgresql
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /Ping-Pong-Piece-Back/node_modules
    environment:
      - DB_USER=eladriere
      - DB_PASSWORD=password
      - DB_PORT=5432
      - DB_NAME=Ping-Pong-Piece
      - HOST=postgresql
    command: npm run start
    networks:
      - app-network

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "Ping-Pong-Piece"
      POSTGRES_USER: "eladriere"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge